name       : gnome-epub-thumbnailer
version    : '1.5'
release    : 2
source     :
    - https://download.gnome.org/sources/gnome-epub-thumbnailer/1.5/gnome-epub-thumbnailer-1.5.tar.xz : 308210f5800219f64cae4828e59bb8e6e4c53b888048cf487221aeb4337d791a
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Thumbnailer for EPub and MOBI books
description: |
    Thumbnailer for EPub and MOBI books
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libarchive)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
