name       : gnome-epub-thumbnailer
version    : '1.6'
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-epub-thumbnailer/1.6/gnome-epub-thumbnailer-1.6.tar.xz : b502420d9b02ea0b0fc7986ef5a091a12b2286be14fed9e47594fe9fa0c5898e
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Thumbnailer for EPub and MOBI books
description: |
    Thumbnailer for EPub and MOBI books
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libarchive)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
